# Generated by Django 5.1.1 on 2024-11-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='imgSrc',
            field=models.CharField(default='', max_length=500),
        ),
    ]
